#!/bin/bash

# 					### Сборка проекта esr10/12V ###

# $1 - в качестве параметра необходимо передать config esr 
# $2 - второй параметр какую сборку необходимо выполнить
# для которого планируете осуществлять сборку (config-esr10; config-esr12V)

cd ~/esr-ldk-4-1-x
make clean
make unconfig
make $1
if [[ $? != 0 ]] ; then
	echo "ERROR: input configuration with build esr: config-esr10 or config-esr12V"
	exit 1
fi
make uboot
if [[ $? != 0 ]] ; then
	echo "ERROR uboot"
	exit 1
elif [[ $2 == 1 ]] ; then
	echo "UBOOT DONE"
	exit 0
fi
make linux-userspace
if [[ $? != 0 ]] ; then
	echo "ERROR linux-userspace"
	exit 1
elif [[ $2 == 2 ]] ; then
	echo "KERNEL DONE"
	exit 0
fi
make apps-all
if [[ $? -eq 0 ]] ; then 
	make firmware-initramfs
else
	make apps-all
	if [[ $? -eq 0 ]] ; then 
		make firmware-initramfs
	else
		make apps-all
		if [[ $? -eq 0 ]] ; then 
			make firmware-initramfs
		fi
	fi
fi

echo "BUILD ESR DONE"
exit 0
